**Chi-Square test**
> **A statistical test used to determine if there's a significant  association between two categorical variables.**

>  This test is used for making claims about the frequencies of categorical data.
* Because it is testing frequencies rather than population parameters, this test is known as a non-parametric test.
* **p-value <0.05** :Reject the null hypothesis(significant association exists)
* **p-value >0.05** :Fail to reject the null hypothesis(no significant association exists)

In [1]:
# importing libraries
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
# Data from superbowl
data = pd.read_csv(r"superbowl.csv")
data.head()

   Super Bowl Coin Toss Outcome Coin Toss Winner Game Winner
0           1             Heads        Home Team   Home Team
1           2             Tails        Home Team   Away Team
2           3             Heads        Home Team   Home Team
3           4             Tails        Away Team   Home Team
4           5             Tails        Home Team   Away Team

In [3]:
data['Coin Toss Winner'].value_counts()

Coin Toss Winner
Away Team    30
Home Team    25
Name: count, dtype: int64

In [4]:
data['Game Winner'].value_counts()

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [5]:
coin_toss_counts=data['Coin Toss Outcome'].value_counts().sort_index()
coin_toss_counts

Coin Toss Outcome
Heads    26
Tails    29
Name: count, dtype: int64

In [6]:
fair_coin_expected=[sum(coin_toss_counts)/2,sum(coin_toss_counts)/2]
fair_coin_expected

[27.5, 27.5]

In [7]:
fair_coin_observed=coin_toss_counts.values
fair_coin_observed

array([26, 29])

In [8]:
#testing whether its a fair coin
fair_coin_result=stats.chisquare(fair_coin_observed,fair_coin_expected)
fair_coin_result

Power_divergenceResult(statistic=np.float64(0.16363636363636364), pvalue=np.float64(0.6858304344516056))

In [9]:
fair_gamewinner_counts=data['Game Winner'].value_counts()
fair_gamewinner_counts

Game Winner
Away Team    31
Home Team    24
Name: count, dtype: int64

In [10]:
observed = fair_gamewinner_counts.values
observed

array([31, 24])

In [11]:
expected=[sum(fair_gamewinner_counts)/2,sum(fair_gamewinner_counts)/2]
expected

[27.5, 27.5]

In [12]:
results=stats.chisquare(observed,expected)
results

Power_divergenceResult(statistic=np.float64(0.8909090909090909), pvalue=np.float64(0.34523107177184))

**whats a boolean index** - filtering data using conditional statements, evaluate **True** or **False**

In [17]:
nfl_data=pd.read_csv(r"nfl_games.csv")
nfl_data.head()

,date,season,neutral,playoff,team1,team2,elo1,elo2,elo_prob1,score1,score2,result1
0,1920-09-26,1920,0,0,RII,STP,1503.947,1300.000,0.824651,48,0,1.0
1,1920-10-03,1920,0,0,AKR,WHE,1503.420,1300.000,0.824212,43,0,1.0
2,1920-10-03,1920,0,0,RCH,ABU,1503.420,1300.000,0.824212,10,0,1.0
3,1920-10-03,1920,0,0,DAY,COL,1493.002,1504.908,0.575819,14,0,1.0
4,1920-10-03,1920,0,0,RII,MUN,1516.108,1478.004,0.644171,45,0,1.0

In [18]:
# Narrow to relevant rows
nfl_data = nfl_data[(nfl_data["neutral"] == 0) & (nfl_data["playoff"] == 0) & (nfl_data["season"] >= 1966 )]
# Engineer a new feature
nfl_data.loc[nfl_data["result1"] == 0, "Game Winner"] = "Away Team"
nfl_data.loc[nfl_data["result1"] == 1, "Game Winner"] = "Home Team"

game_winner_counts_nfl = nfl_data["Game Winner"].value_counts().sort_index()
game_winner_counts_nfl

Game Winner
Away Team    5265
Home Team    7066
Name: count, dtype: int64